tables:
  - todosTable
  - usersTable

types:
  - name: Todo
    ref: todosTable
    fields:
      - name: text
        type: String
        required: true
      - name: completed
        type: Boolean
        required: false

  - name: User
    ref: usersTable
    fields:
      - name: email
        type: String
        required: true
      - name: password
        type: String
        required: true
